// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.textanalytics;

import com.azure.ai.textanalytics.implementation.TextAnalyticsClientImpl;
import com.azure.core.annotation.ServiceClient;

/** Initializes a new instance of the asynchronous TextAnalyticsClient type. */
@ServiceClient(builder = TextAnalyticsClientBuilder.class, isAsync = true)
public final class TextAnalyticsAsyncClient {
    private final TextAnalyticsClientImpl serviceClient;

    /**
     * Initializes an instance of TextAnalyticsClient client.
     *
     * @param serviceClient the service client implementation.
     */
    TextAnalyticsAsyncClient(TextAnalyticsClientImpl serviceClient) {
        this.serviceClient = serviceClient;
    }
}
