// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.textanalytics;

import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.HttpMethod;
import com.azure.core.http.HttpPipeline;
import com.azure.core.util.serializer.SerializerAdapter;

/** Initializes a new instance of the asynchronous TextAnalyticsClient type. */
@ServiceClient(builder = TextAnalyticsClientBuilder.class, isAsync = true)
public final class TextAnalyticsModelClient extends TextAnalyticsClient {
    /**
     * Initializes an instance of TextAnalyticsClient client.
     *
     */
    TextAnalyticsModelClient(SerializerAdapter serializerAdapter, HttpPipeline httpPipeline, String endpoint) {
        super(serializerAdapter, httpPipeline, endpoint);
    }

    /**
     * The API returns a list of recognized entities with links to a well-known knowledge base. See the &lt;a
     * href="https://aka.ms/talangs"&gt;Supported languages in Text Analytics API&lt;/a&gt; for the list of enabled
     * languages.
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public EntitiesLinkingRequestSpec entitiesLinking() {
        return new EntitiesLinkingRequestSpec(getSerializerAdapter(), getHttpPipeline())
                .url("{Endpoint}/text/analytics/v3.1-preview.3/entities/linking")
                .param("Endpoint", getEndpoint())
                .httpMethod(HttpMethod.POST)
                .header("Accept", "application/json, text/json");
    }
}
